
package com.zgm.webservices.client.server;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WebServicesTestService", targetNamespace = "http://server.webservices.zgm.com/", wsdlLocation = "http://localhost:8080/hello?wsdl")
public class WebServicesTestService
    extends Service
{

    private final static URL WEBSERVICESTESTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.zgm.webservices.client.server.WebServicesTestService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.zgm.webservices.client.server.WebServicesTestService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/hello?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/hello?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WEBSERVICESTESTSERVICE_WSDL_LOCATION = url;
    }

    public WebServicesTestService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServicesTestService() {
        super(WEBSERVICESTESTSERVICE_WSDL_LOCATION, new QName("http://server.webservices.zgm.com/", "WebServicesTestService"));
    }

    /**
     * 
     * @return
     *     returns WebServicesTest
     */
    @WebEndpoint(name = "WebServicesTestPort")
    public WebServicesTest getWebServicesTestPort() {
        return super.getPort(new QName("http://server.webservices.zgm.com/", "WebServicesTestPort"), WebServicesTest.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServicesTest
     */
    @WebEndpoint(name = "WebServicesTestPort")
    public WebServicesTest getWebServicesTestPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.webservices.zgm.com/", "WebServicesTestPort"), WebServicesTest.class, features);
    }

}
